package primero;
// Generated 27-nov-2019 22:57:50 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private Byte empNo;
	private Departamentos departamentos;
	private String apellido;
	private String oficio;
	private int dir;
	private Date fechaAlta;
	private float salario;

	public Empleados() {
	}

	public Empleados(Departamentos departamentos, String apellido, String oficio, int dir, Date fechaAlta,
			float salario) {
		this.departamentos = departamentos;
		this.apellido = apellido;
		this.oficio = oficio;
		this.dir = dir;
		this.fechaAlta = fechaAlta;
		this.salario = salario;
	}

	public Byte getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(Byte empNo) {
		this.empNo = empNo;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public int getDir() {
		return this.dir;
	}

	public void setDir(int dir) {
		this.dir = dir;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public float getSalario() {
		return this.salario;
	}

	public void setSalario(float salario) {
		this.salario = salario;
	}

}
